#!/bin/bash
#
# Tile38 Startup Script
#

set -euo pipefail

if [[ -e /data/config ]]; then
    jq --arg pass "${TILE38_PASSWORD}" '.requirepass = $pass' /data/config > /tmp/config && mv /tmp/config /data/config
else
    jq -n --arg pass "${TILE38_PASSWORD}" '{"requirepass": $pass}' > /data/config
fi

tile38-server -d /data
